### ISSUE TITLE
Oriental Asian First Names (Re-opened)

### ISSUE THREAD

**Issue by sengbinggo** [MicrosoftDocs/learn#10]
![image](https://user-images.githubusercontent.com/39364632/40459949-deb979be-5f36-11e8-8ff4-ee953320e1f7.png)

My first name is "Seng Bing" not "Seng". How can I make Microsoft's products more Asian/Oriental name friendly?

May I know how to close this issue please?

**Comment by barlanmsft** [comment]
Hi @sengbinggo - here's how you can change the name on your Microsoft account. 

1. Sign in to the [Your info page on the Microsoft account website](http://account.microsoft.com/profile).
2. Under your name, select **Edit name**. If there’s no name listed yet, select **Add name**.  
3. Enter the name you want, then choose **Save**. Some names may not be allowed if they contain blocked words or phrases. If you get an error when you enter your name, try a nickname instead.

You should be able to input your first name as "Seng Bing" rather than just "Seng". I've just tested this to confirm with a test account, and it worked: 

What text I put in: 
![image](https://user-images.githubusercontent.com/16927294/41374230-70fb85b2-6f07-11e8-8cad-164e8bae59e0.png)

What it shows as on the account page: 
![image](https://user-images.githubusercontent.com/16927294/41374195-5cbcec76-6f07-11e8-9407-b63c4c16b53b.png)

How it appears on the top of the page: 
![image](https://user-images.githubusercontent.com/16927294/41374275-8da71fd2-6f07-11e8-9c05-3cc4eaada04c.png)

For now, I'm going to close this issue. If you still have questions about your Microsoft account, we also offer support [here](https://support.microsoft.com/contactus/).
